//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace oil
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class gatewayEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“gatewayEntities”部分中的连接字符串初始化新 gatewayEntities 对象。
        /// </summary>
        public gatewayEntities() : base("name=gatewayEntities", "gatewayEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 gatewayEntities 对象。
        /// </summary>
        public gatewayEntities(string connectionString) : base(connectionString, "gatewayEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 gatewayEntities 对象。
        /// </summary>
        public gatewayEntities(EntityConnection connection) : base(connection, "gatewayEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<BaseInfo> BaseInfo
        {
            get
            {
                if ((_BaseInfo == null))
                {
                    _BaseInfo = base.CreateObjectSet<BaseInfo>("BaseInfo");
                }
                return _BaseInfo;
            }
        }
        private ObjectSet<BaseInfo> _BaseInfo;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Data1> Data1
        {
            get
            {
                if ((_Data1 == null))
                {
                    _Data1 = base.CreateObjectSet<Data1>("Data1");
                }
                return _Data1;
            }
        }
        private ObjectSet<Data1> _Data1;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 BaseInfo EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToBaseInfo(BaseInfo baseInfo)
        {
            base.AddObject("BaseInfo", baseInfo);
        }
    
        /// <summary>
        /// 用于向 Data1 EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToData1(Data1 data1)
        {
            base.AddObject("Data1", data1);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="gatewayModel", Name="BaseInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BaseInfo : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 BaseInfo 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static BaseInfo CreateBaseInfo(global::System.Int32 id)
        {
            BaseInfo baseInfo = new BaseInfo();
            baseInfo.id = id;
            return baseInfo;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Chang
        {
            get
            {
                return _Chang;
            }
            set
            {
                OnChangChanging(value);
                ReportPropertyChanging("Chang");
                _Chang = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Chang");
                OnChangChanged();
            }
        }
        private global::System.String _Chang;
        partial void OnChangChanging(global::System.String value);
        partial void OnChangChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Zhan
        {
            get
            {
                return _Zhan;
            }
            set
            {
                OnZhanChanging(value);
                ReportPropertyChanging("Zhan");
                _Zhan = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Zhan");
                OnZhanChanged();
            }
        }
        private global::System.String _Zhan;
        partial void OnZhanChanging(global::System.String value);
        partial void OnZhanChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GuoLu
        {
            get
            {
                return _GuoLu;
            }
            set
            {
                OnGuoLuChanging(value);
                ReportPropertyChanging("GuoLu");
                _GuoLu = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GuoLu");
                OnGuoLuChanged();
            }
        }
        private global::System.String _GuoLu;
        partial void OnGuoLuChanging(global::System.String value);
        partial void OnGuoLuChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SheBei
        {
            get
            {
                return _SheBei;
            }
            set
            {
                OnSheBeiChanging(value);
                ReportPropertyChanging("SheBei");
                _SheBei = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SheBei");
                OnSheBeiChanged();
            }
        }
        private global::System.String _SheBei;
        partial void OnSheBeiChanging(global::System.String value);
        partial void OnSheBeiChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Max
        {
            get
            {
                return _Max;
            }
            set
            {
                OnMaxChanging(value);
                ReportPropertyChanging("Max");
                _Max = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Max");
                OnMaxChanged();
            }
        }
        private Nullable<global::System.Int32> _Max;
        partial void OnMaxChanging(Nullable<global::System.Int32> value);
        partial void OnMaxChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="gatewayModel", Name="Data1")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Data1 : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Data1 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static Data1 CreateData1(global::System.Int32 id)
        {
            Data1 data1 = new Data1();
            data1.id = id;
            return data1;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SheBei
        {
            get
            {
                return _SheBei;
            }
            set
            {
                OnSheBeiChanging(value);
                ReportPropertyChanging("SheBei");
                _SheBei = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SheBei");
                OnSheBeiChanged();
            }
        }
        private global::System.String _SheBei;
        partial void OnSheBeiChanging(global::System.String value);
        partial void OnSheBeiChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Chang
        {
            get
            {
                return _Chang;
            }
            set
            {
                OnChangChanging(value);
                ReportPropertyChanging("Chang");
                _Chang = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Chang");
                OnChangChanged();
            }
        }
        private global::System.String _Chang;
        partial void OnChangChanging(global::System.String value);
        partial void OnChangChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Zhan
        {
            get
            {
                return _Zhan;
            }
            set
            {
                OnZhanChanging(value);
                ReportPropertyChanging("Zhan");
                _Zhan = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Zhan");
                OnZhanChanged();
            }
        }
        private global::System.String _Zhan;
        partial void OnZhanChanging(global::System.String value);
        partial void OnZhanChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GuoLu
        {
            get
            {
                return _GuoLu;
            }
            set
            {
                OnGuoLuChanging(value);
                ReportPropertyChanging("GuoLu");
                _GuoLu = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GuoLu");
                OnGuoLuChanged();
            }
        }
        private global::System.String _GuoLu;
        partial void OnGuoLuChanging(global::System.String value);
        partial void OnGuoLuChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ZQWD01
        {
            get
            {
                return _ZQWD01;
            }
            set
            {
                OnZQWD01Changing(value);
                ReportPropertyChanging("ZQWD01");
                _ZQWD01 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ZQWD01");
                OnZQWD01Changed();
            }
        }
        private Nullable<global::System.Decimal> _ZQWD01;
        partial void OnZQWD01Changing(Nullable<global::System.Decimal> value);
        partial void OnZQWD01Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ZQGD17
        {
            get
            {
                return _ZQGD17;
            }
            set
            {
                OnZQGD17Changing(value);
                ReportPropertyChanging("ZQGD17");
                _ZQGD17 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ZQGD17");
                OnZQGD17Changed();
            }
        }
        private Nullable<global::System.Decimal> _ZQGD17;
        partial void OnZQGD17Changing(Nullable<global::System.Decimal> value);
        partial void OnZQGD17Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> YQHY20
        {
            get
            {
                return _YQHY20;
            }
            set
            {
                OnYQHY20Changing(value);
                ReportPropertyChanging("YQHY20");
                _YQHY20 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("YQHY20");
                OnYQHY20Changed();
            }
        }
        private Nullable<global::System.Decimal> _YQHY20;
        partial void OnYQHY20Changing(Nullable<global::System.Decimal> value);
        partial void OnYQHY20Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ZQYL02
        {
            get
            {
                return _ZQYL02;
            }
            set
            {
                OnZQYL02Changing(value);
                ReportPropertyChanging("ZQYL02");
                _ZQYL02 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ZQYL02");
                OnZQYL02Changed();
            }
        }
        private Nullable<global::System.Decimal> _ZQYL02;
        partial void OnZQYL02Changing(Nullable<global::System.Decimal> value);
        partial void OnZQYL02Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> RYLL16
        {
            get
            {
                return _RYLL16;
            }
            set
            {
                OnRYLL16Changing(value);
                ReportPropertyChanging("RYLL16");
                _RYLL16 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RYLL16");
                OnRYLL16Changed();
            }
        }
        private Nullable<global::System.Decimal> _RYLL16;
        partial void OnRYLL16Changing(Nullable<global::System.Decimal> value);
        partial void OnRYLL16Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> GSLL10
        {
            get
            {
                return _GSLL10;
            }
            set
            {
                OnGSLL10Changing(value);
                ReportPropertyChanging("GSLL10");
                _GSLL10 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GSLL10");
                OnGSLL10Changed();
            }
        }
        private Nullable<global::System.Decimal> _GSLL10;
        partial void OnGSLL10Changing(Nullable<global::System.Decimal> value);
        partial void OnGSLL10Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> FSWD09
        {
            get
            {
                return _FSWD09;
            }
            set
            {
                OnFSWD09Changing(value);
                ReportPropertyChanging("FSWD09");
                _FSWD09 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FSWD09");
                OnFSWD09Changed();
            }
        }
        private Nullable<global::System.Decimal> _FSWD09;
        partial void OnFSWD09Changing(Nullable<global::System.Decimal> value);
        partial void OnFSWD09Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> DRWD08
        {
            get
            {
                return _DRWD08;
            }
            set
            {
                OnDRWD08Changing(value);
                ReportPropertyChanging("DRWD08");
                _DRWD08 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DRWD08");
                OnDRWD08Changed();
            }
        }
        private Nullable<global::System.Decimal> _DRWD08;
        partial void OnDRWD08Changing(Nullable<global::System.Decimal> value);
        partial void OnDRWD08Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> DCWD07
        {
            get
            {
                return _DCWD07;
            }
            set
            {
                OnDCWD07Changing(value);
                ReportPropertyChanging("DCWD07");
                _DCWD07 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DCWD07");
                OnDCWD07Changed();
            }
        }
        private Nullable<global::System.Decimal> _DCWD07;
        partial void OnDCWD07Changing(Nullable<global::System.Decimal> value);
        partial void OnDCWD07Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> RYYL
        {
            get
            {
                return _RYYL;
            }
            set
            {
                OnRYYLChanging(value);
                ReportPropertyChanging("RYYL");
                _RYYL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RYYL");
                OnRYYLChanged();
            }
        }
        private Nullable<global::System.Decimal> _RYYL;
        partial void OnRYYLChanging(Nullable<global::System.Decimal> value);
        partial void OnRYYLChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> GBWD05
        {
            get
            {
                return _GBWD05;
            }
            set
            {
                OnGBWD05Changing(value);
                ReportPropertyChanging("GBWD05");
                _GBWD05 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GBWD05");
                OnGBWD05Changed();
            }
        }
        private Nullable<global::System.Decimal> _GBWD05;
        partial void OnGBWD05Changing(Nullable<global::System.Decimal> value);
        partial void OnGBWD05Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> WKWD04
        {
            get
            {
                return _WKWD04;
            }
            set
            {
                OnWKWD04Changing(value);
                ReportPropertyChanging("WKWD04");
                _WKWD04 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WKWD04");
                OnWKWD04Changed();
            }
        }
        private Nullable<global::System.Decimal> _WKWD04;
        partial void OnWKWD04Changing(Nullable<global::System.Decimal> value);
        partial void OnWKWD04Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PYWD03
        {
            get
            {
                return _PYWD03;
            }
            set
            {
                OnPYWD03Changing(value);
                ReportPropertyChanging("PYWD03");
                _PYWD03 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PYWD03");
                OnPYWD03Changed();
            }
        }
        private Nullable<global::System.Decimal> _PYWD03;
        partial void OnPYWD03Changing(Nullable<global::System.Decimal> value);
        partial void OnPYWD03Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> GFPL14
        {
            get
            {
                return _GFPL14;
            }
            set
            {
                OnGFPL14Changing(value);
                ReportPropertyChanging("GFPL14");
                _GFPL14 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GFPL14");
                OnGFPL14Changed();
            }
        }
        private Nullable<global::System.Decimal> _GFPL14;
        partial void OnGFPL14Changing(Nullable<global::System.Decimal> value);
        partial void OnGFPL14Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> RQLJ
        {
            get
            {
                return _RQLJ;
            }
            set
            {
                OnRQLJChanging(value);
                ReportPropertyChanging("RQLJ");
                _RQLJ = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RQLJ");
                OnRQLJChanged();
            }
        }
        private Nullable<global::System.Decimal> _RQLJ;
        partial void OnRQLJChanging(Nullable<global::System.Decimal> value);
        partial void OnRQLJChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> RYLJ
        {
            get
            {
                return _RYLJ;
            }
            set
            {
                OnRYLJChanging(value);
                ReportPropertyChanging("RYLJ");
                _RYLJ = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RYLJ");
                OnRYLJChanged();
            }
        }
        private Nullable<global::System.Decimal> _RYLJ;
        partial void OnRYLJChanging(Nullable<global::System.Decimal> value);
        partial void OnRYLJChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> SLLJQ
        {
            get
            {
                return _SLLJQ;
            }
            set
            {
                OnSLLJQChanging(value);
                ReportPropertyChanging("SLLJQ");
                _SLLJQ = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SLLJQ");
                OnSLLJQChanged();
            }
        }
        private Nullable<global::System.Decimal> _SLLJQ;
        partial void OnSLLJQChanging(Nullable<global::System.Decimal> value);
        partial void OnSLLJQChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> SLLJY
        {
            get
            {
                return _SLLJY;
            }
            set
            {
                OnSLLJYChanging(value);
                ReportPropertyChanging("SLLJY");
                _SLLJY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SLLJY");
                OnSLLJYChanged();
            }
        }
        private Nullable<global::System.Decimal> _SLLJY;
        partial void OnSLLJYChanging(Nullable<global::System.Decimal> value);
        partial void OnSLLJYChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> YDLJ
        {
            get
            {
                return _YDLJ;
            }
            set
            {
                OnYDLJChanging(value);
                ReportPropertyChanging("YDLJ");
                _YDLJ = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("YDLJ");
                OnYDLJChanged();
            }
        }
        private Nullable<global::System.Decimal> _YDLJ;
        partial void OnYDLJChanging(Nullable<global::System.Decimal> value);
        partial void OnYDLJChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> RQDH
        {
            get
            {
                return _RQDH;
            }
            set
            {
                OnRQDHChanging(value);
                ReportPropertyChanging("RQDH");
                _RQDH = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RQDH");
                OnRQDHChanged();
            }
        }
        private Nullable<global::System.Decimal> _RQDH;
        partial void OnRQDHChanging(Nullable<global::System.Decimal> value);
        partial void OnRQDHChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> RYDH
        {
            get
            {
                return _RYDH;
            }
            set
            {
                OnRYDHChanging(value);
                ReportPropertyChanging("RYDH");
                _RYDH = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RYDH");
                OnRYDHChanged();
            }
        }
        private Nullable<global::System.Decimal> _RYDH;
        partial void OnRYDHChanging(Nullable<global::System.Decimal> value);
        partial void OnRYDHChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> YDDH
        {
            get
            {
                return _YDDH;
            }
            set
            {
                OnYDDHChanging(value);
                ReportPropertyChanging("YDDH");
                _YDDH = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("YDDH");
                OnYDDHChanged();
            }
        }
        private Nullable<global::System.Decimal> _YDDH;
        partial void OnYDDHChanging(Nullable<global::System.Decimal> value);
        partial void OnYDDHChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nian
        {
            get
            {
                return _Nian;
            }
            set
            {
                OnNianChanging(value);
                ReportPropertyChanging("Nian");
                _Nian = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nian");
                OnNianChanged();
            }
        }
        private global::System.String _Nian;
        partial void OnNianChanging(global::System.String value);
        partial void OnNianChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Yue
        {
            get
            {
                return _Yue;
            }
            set
            {
                OnYueChanging(value);
                ReportPropertyChanging("Yue");
                _Yue = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Yue");
                OnYueChanged();
            }
        }
        private global::System.String _Yue;
        partial void OnYueChanging(global::System.String value);
        partial void OnYueChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ri
        {
            get
            {
                return _Ri;
            }
            set
            {
                OnRiChanging(value);
                ReportPropertyChanging("Ri");
                _Ri = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ri");
                OnRiChanged();
            }
        }
        private global::System.String _Ri;
        partial void OnRiChanging(global::System.String value);
        partial void OnRiChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ShiJian
        {
            get
            {
                return _ShiJian;
            }
            set
            {
                OnShiJianChanging(value);
                ReportPropertyChanging("ShiJian");
                _ShiJian = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ShiJian");
                OnShiJianChanged();
            }
        }
        private Nullable<global::System.DateTime> _ShiJian;
        partial void OnShiJianChanging(Nullable<global::System.DateTime> value);
        partial void OnShiJianChanged();

        #endregion
    
    }

    #endregion
    
}
